### ISSUE TITLE
Windows support please?

### ISSUE THREAD

**Issue by magestican** [MrBoolean/gulp-codeclimate-reporter#3]
I would be really grateful if you added some windows support.
This is basically what happens when I add this module into my gulp process on a windows machine 

 Command failed: C:\WINDOWS\system32\cmd.exe /s /c "CODECLIMATE_REPO_TOKEN=1234 node_modules/codeclimate-test-reporter/bin/codeclimate.js < "C:\callscreen\coverage\PhantomJS 2.0.0 (Windows 8 0.0.0)\lcov.info""
'CODECLIMATE_REPO_TOKEN' is not recognized as an internal or external command,
operable program or batch file.

I have all my servers on windows and so it would be really useful if this worked in windows, thanks.

I have to note that I can manually execute codeclimate and upload my lcov files but this is certainly missing :(

**Comment by m19c** [comment]
Checkout the changes. Once there is no problem I will release a new minor version of `gulp-codeclimate-reporter`.

_Note:_ The commit takes care of the powershell!

**Comment by magestican** [comment]
Oh jee! Thank you very much. 
I will let you know the results soon fyi :D

**Comment by magestican** [comment]
Can you re-release? NPM is not pulling your latest changes since the version of the repo has not changed, thanks!

Update : it still doesnt work, the error is now that the path to lcov file is wrong, probably an issue with single and double slash?
